### PR TITLE
Add production build(er)

### LINKED ISSUE #19: Compile production app & put it somewhere
My original plan was https://a8cteam51.github.io/strikestart/; I think we can still do that but we'll need to tweak some of our configuration a bit.

There's also [this static setup](https://medium.com/superhighfives/an-almost-static-stack-6df0a2791319), but I think that's more geared toward getting SEO-love, which I quite frankly don't give a damn about (at least right now). 

I think I should be able to make this happen by following [these instructions](https://github.com/a8cteam51/strikestart#github-pages).

Will want to update the README as well to reflect that process.

### PR DESCRIPTION
**Pull request by sarahmonster**
This fixes #19 and provides two methods of deployment.

I wanted to put the build on github pages but it's not quite perfect, which you can see at a8cteam51.github.io/strikestart. I suspect that's related to [this issue](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#notes-on-client-side-routing) and could probably be fixed given further investigation.

However, in the interests of getting something that works up and running, I've included an alternate deployment method which seems to work properly, using now.

Both deployment methods are outlined in the README.

Note that this is stacked on #43 because otherwise resolving merge conflicts would likely have been a beast.

I also needed to change all the paths to relative ones because for whatever reason the absolute paths caused errors when I ran `npm run build`. If there's an easy fix there I'm happy to change them, but again, it wasn't worth the time to investigate the issue further right now.

### CODE REVIEW

**Comment by sarahmonster** [comment]
^ see updated comments; this is ready to go once #43 is merged.

**Comment by sarahmonster** [comment]
I've just realised that now changes the URL every time you deploy, so we'll either need to use a shortlink service where we can change the page that's redirected to (which is rather annoying), or get the Github pages thing working properly, which isn't quite there yet. 😢 Booooo.

I'm now also having troubles getting now to display anything other than a white screen of death, so I might be back to square one here.

**Comment by sarahmonster** [comment]
So, the issue I'm having with Github pages is sort of twofold:

1. The / path doesn't render properly. So when you load https://a8cteam51.github.io/strikestart/ only the navigation component renders. I thought maybe it was an issue with the redirect, so I changed the code to `<Route exact path="/" component={ StepOne } />` but still had the same issue.

2. When you navigate through the site, the URL isn't represented properly, so it turns into https://a8cteam51.github.io/step-one for instance. Everything works properly, just the URL looks wrong. Loading https://a8cteam51.github.io/step-one doesn't work properly, either.

Technically everything kind of works, and you can navigate through the steps so long as you click on the "1" link to get started, so I can probably do something to hack my way around that (background image pointing to the 1 maybe?) but obviously it's less than ideal.

I'm using the technique outlined here to deal with the weirdness of routing: https://github.com/rafrex/spa-github-pages, but it doesn't seem to working quite right. If it's an issue with the technique there, I could file a bug with them once I've a better idea what's not working properly!

**Comment by danielwrobert** [comment]
I think I see the issue. After reading through the docs, it looks like you need to add the `basename` attribute to the `BrowserRouter` component from React Router.

You can update that [here](https://github.com/a8cteam51/strikestart/blob/e2e931248555577f128ea6d8df4cf0bec23c509c/src/components/App/index.js#L32). You just need to change `<BrowserRouter>` to `<BrowserRouter basename="/strikestart" />`.

I _think_ that should do the trick, that's all I see missing from the instructions, at this point.

**Comment by danielwrobert** [comment]
Oh, I think we also need to add the `.nojekyll` file from [here](https://github.com/rafrex/spa-github-pages/blob/gh-pages/.nojekyll).

The `.nojekyll` file [turns off Jekyll for GitHub Pages](https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/).

**Pull request merged**
